name: Build and Deploy Frontend
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: v23.7.0

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          VITE_API_URL: ${{ vars.API_URL_DEV }}
          VITE_WS_URL: ${{ vars.WS_URL_DEV }}
          VITE_MSAL_CLIENT_ID: ${{ vars.MSAL_CLIENT_ID_DEV }}
          VITE_MSAL_TENANT_ID: ${{ vars.MSAL_TENANT_ID_DEV }}
          VITE_MSAL_REDIRECT_URI: ${{ vars.MSAL_REDIRECT_URI_DEV }}
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to S3
        run: aws s3 sync dist s3://iu-quiz-frontend-dev --delete

      - name: Invalidate CloudFront Cache
        run: |
          DISTRIBUTION_ID=$(aws cloudfront list-distributions --output json | jq -r '.DistributionList.Items[] | select(.Aliases.Items[] == "dev.iu-quiz.de") | .Id')
          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/*"

#TODO: Invalidate CloudFront  distribution
# List CloudFront Distribution ID by aws cli and filter on dev distribution with --query
# aws cloudfront list-distributions --query "QueryToOutputIDWhereAliasContainsDev"
# aws cloudfront create-invalidation --distribution-id DISTRIBUTIONID --paths "/*"
